### ISSUE TITLE
Update dag-jose format and deps

### ISSUE THREAD

**Issue by v-stickykeys** [3box/ceramic-integration-tests#59]
```
	2021-06-29T08:04:41.032Z	Connecting to peers found in 'https://raw.githubusercontent.com/ceramicnetwork/peerlist/main/dev-unstable.json'
	2021-06-29T08:04:41.177Z	TypeError: multiaddr_1.Multiaddr is not a constructor
	2021-06-29T08:04:41.177Z	at /app/node_modules/@ceramicnetwork/ipfs-topology/lib/ipfs-topology.js:99:78
	2021-06-29T08:04:41.177Z	at Array.map (<anonymous>)
	2021-06-29T08:04:41.177Z	at IpfsTopology._dynamicBoostrapList (/app/node_modules/@ceramicnetwork/ipfs-topology/lib/ipfs-topology.js:99:66)
	2021-06-29T08:04:41.177Z	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	2021-06-29T08:04:41.177Z	at async IpfsTopology.forceConnection (/app/node_modules/@ceramicnetwork/ipfs-topology/lib/ipfs-topology.js:76:25)
	2021-06-29T08:04:41.177Z	at async IpfsTopology.start (/app/node_modules/@ceramicnetwork/ipfs-topology/lib/ipfs-topology.js:81:9)
	2021-06-29T08:04:41.177Z	at async IpfsDaemon.start (/app/node_modules/@ceramicnetwork/ipfs-daemon/lib/ipfs-daemon.js:160:9)
```

**Comment by v-stickykeys** [comment]
Versions that are working for me on stats agent and should work here are 
```
├── @ceramicnetwork/ipfs-daemon@1.0.7
├── @ceramicnetwork/streamid@1.0.2
├── dag-jose@1.0.0
├── ipfs@0.55.4
├── ipfs-http-client@50.1.2
├── multiformats@4.6.3
└── uint8arrays@2.1.5
```
