### ISSUE TITLE
Key revocation test failure

### ISSUE THREAD

**Issue by v-stickykeys** [3box/ceramic-integration-tests#87]
Tests are failing repeatedly but inconsistently in the same place for 2 of 3 different configurations.

local_node-private [logs](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Fecs$252Fceramic-dev-tests/log-events/smoke_tests$252Fsmoke_tests$252Fb6c1af1ee66a40b2a6ed5024ef52d074), [discord alert](https://discord.com/channels/484729862368526356/877191109275713586/904654811654418432)
```
'Error while storing commit to IPFS: FetchError: request to http://localhost:5011/api/v0/dag/put?format=dag-jose&input-enc=raw&hash=sha2-256 failed, reason: write EPIPE'
--
'Closing Ceramic instance'
'Error while loading commit CID bagcqceravxuaovfg33bj6llnikzik57e75w7k3fshm5fa7aby22tnmso4wqa from IPFS: TimeoutError: Request timed out'
TimeoutError: Request timed out
at Timeout.<anonymous> (/app/node_modules/ipfs-utils/src/http.js:40:16)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
'Error while loading commit CID bagcqcera5jc4qaifvssxfrplyigim4qqot6aejggyv6uerwdyrq6ojphzqxa from IPFS: TimeoutError: Request timed out'
'Error while loading commit CID bagcqcera2u2xjarqbbf52y52ytyf2prnqtqgoixbd7cy4lxj74p7uznzbhya from IPFS: TimeoutError: Request timed out'
'Ceramic instance closed successfully'
FAIL src/__tests__/key_revocation.ts (14.023 s)
✕ key revocation (6298 ms)
● key revocation
FetchError: request to http://localhost:5011/api/v0/dag/put?format=dag-jose&input-enc=raw&hash=sha2-256 failed, reason: write EPIPE
at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1461:11)
Starting test in environment: local_node-private
```
private-public [logs](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Fecs$252Fceramic-dev-tests/log-events/smoke_tests$252Fsmoke_tests$252F3e8b90d670bc47b2b49a623959a8425f), [discord alert](https://discord.com/channels/484729862368526356/877191109275713586/904045480537903174)

```
HTTP request to 'https://ceramic-dev.3boxlabs.com/api/v0/streams/kjzl6cwe1jw14bdoghujl0j746pjcc92hwafxo1zvyww0wobxpdg7ck4akrfe68?sync=0' failed with status 'Bad Gateway': <html>
--
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
at Object.fetchJson (node_modules/@ceramicnetwork/common/src/utils/http-utils.ts:19:11)
at runMicrotasks (<anonymous>)
at Function._load (node_modules/@ceramicnetwork/http-client/src/document.ts:109:23)
at Document._syncState (node_modules/@ceramicnetwork/http-client/src/document.ts:59:19)
Starting test in environment: private-public
Creating ceramic via http client, connected to https://ceramic-private-dev.3boxlabs.com
Ceramic client connected successfully to https://ceramic-private-dev.3boxlabs.com
Creating ceramic via http client, connected to https://ceramic-dev.3boxlabs.com
Ceramic client connected successfully to https://ceramic-dev.3boxlabs.com
(node:54) V8: /app/node_modules/@ceramicnetwork/streamid/node_modules/borc/src/decoder.asm.js:3 Linking failure in asm.js: Unexpected stdlib member
(node:54) V8: /app/node_modules/dag-jose-utils/node_modules/borc/src/decoder.asm.js:3 Linking failure in asm.js: Unexpected stdlib member
(node:54) V8: /app/node_modules/borc/src/decoder.asm.js:3 Linking failure in asm.js: Unexpected stdlib member
(node:54) V8: /app/node_modules/dag-cbor-links/node_modules/borc/src/decoder.asm.js:3 Linking failure in asm.js: Unexpected stdlib member
FAIL src/__tests__/key_revocation.ts (7.051 s)
✕ key revocation (316 ms)
● key revocation
HTTP request to 'https://ceramic-private-dev.3boxlabs.com/api/v0/streams' failed with status 'Bad Gateway': <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
at Object.fetchJson (node_modules/@ceramicnetwork/common/src/utils/http-utils.ts:19:11)
at runMicrotasks (<anonymous>)
at Function.createFromGenesis (node_modules/@ceramicnetwork/http-client/src/document.ts:74:23)
at CeramicClient.createStreamFromGenesis (node_modules/@ceramicnetwork/http-client/src/ceramic-http-client.ts:111:20)
Starting test in environment: private-public
```

**Comment by v-stickykeys** [comment]
This is passing so going to close now
